site_name: Automações SPF
site_description: Internal reference and guides for automation scripts and workflows
site_author: SEPLAG
repo_url: https://github.com/SPF-SEPLAG/docs-spf
theme:
  name: material
  features:
#    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
nav:
  - Home: index.md
  - Automações: 
    - Dados de pagamento em ordem cronológica: automacoes/filtragem_excel.md
  - Dashboards:
      - PAC e Contratos: dashboards/dccc/intro.md
      - Execução Orçamentária:
        - Introdução: dashboards/dpo/intro.md
        - Projeto e Cronograma: dashboards/dpo/projeto.md
        - Integração das ferramentas e fluxo geral: dashboards/dpo/fluxo_geral.md
        - Download da planilha e geração dos Tokens: dashboards/dpo/download.md
        - Credenciamento Sharepoint e Github:  dashboards/dpo/placeholder2.md
        - Pré-processamento dos dados: dashboards/dpo/pre_processamento_dados.md
        - Workflow Github Actions: dashboards/dpo/placeholder3.md
  - Guias e tutoriais:
    - Power BI: 
      - Carregar dados PBI: guides/pbi/carregar_dados.md
      - Configurar Modelo Semântico PBI: guides/pbi/configurar_modelo_semantico.md
    - Github:
      - Criar repositório github: guides/github/criar_repo.md
      - Github Actions: guides/github/conceitos/github_actions.md
      - Criar Secrets e PAT: guides/github/criar_secrets_pat.md
      - Access Token e Refresh Token: guides/github/conceitos/access_refresh_tokens.md
      - Criar SSH: guides/github/conceitos/criar_ssh.md
    - Camg: 
      - Configurar proxy: guides/camg/config_proxy.md
      - Configurar ssh: guides/camg/config_ssh.md
